#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#set shell that sxhkd uses to execute commands:
#export SXHKD_SHELL=/usr/bin/bash

#start bspwm and sxhkd
#sxhkd -f 100 -c /home/$USER/.config/sxhkd/sxhkdrc &

polybar &
nitrogen --restore
picom &
dunst &
lxpolkit &
/usr/lib/geoclue-2.0/demos/agent &
tlp start

bspc monitor -d 1 2 3 4 5

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width         2
bspc config window_gap           12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color	 "#701e1e"
bspc config focused_border_color	"#f73d3d"
bspc config active_border_color	"#ffa6a6"
bspc config focus_follows_pointer	true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

